todo/api/urls.py
from django.conf.urls import url, include

from rest_framework.routers import DefaultRouter

from .views import ToDoViewSet

router = DefaultRouter()
router.register(r'todo', ToDoViewSet)

urlpatterns = [
    url(r'^v1/', include(router.urls)),
]

todo/todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("todo_list.urls")),
    url(r'^api/', include('api.urls'))
]

todo/todo_list/urls.py
from django.conf.urls import url

from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new_task, name='new_task'),
    url(r'^edit/(?P<pk>\d+)$', views.edit, name='edit_task'),
    url(r'^done-list', views.done_tasks_list, name='done_list'),
    url(r'^done/(?P<pk>\d+)$', views.make_task_done, name='make_done'),
    url(r'^make_in_progress/(?P<pk>\d+)$', views.make_task_in_progress, name='make_in_progress'),
]

todo/todo_list/models.py
from django.db import models

class TODO(models.Model):
    header = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    isDone = models.BooleanField(default=False)

    def __str__(self):
        return self.header

    class Meta:
        ordering = ('-pk',)

todo/todo_list/forms.py
from django.forms import ModelForm, TextInput, Textarea

from .models import TODO


class CreateTaskForm(ModelForm):
    class Meta:
        model = TODO
        fields = ['header', 'description']
        widgets = {
            'header': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control',
                                             'rows': 5}),        }

todo/api/views.py
from rest_framework import viewsets

from todo_list.models import TODO
from .serializers import TODOSerializer

class ToDoViewSet(viewsets.ModelViewSet):
    queryset = TODO.objects.all()
    serializer_class = TODOSerializer

todo/todo_list/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.http import require_POST

from .models import TODO
from .forms import CreateTaskForm

def index(request):
    data = TODO.objects.filter(isDone=False)
    return render(request, "todo/index.html", {"data":data})

def new_task(request):
    if request.method == 'POST':
        form = CreateTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todo:index'))
    else:
        form = CreateTaskForm()
    return render(request, 'todo/create_edit_task.html', {'form': form, 'active': 'new task'})

def edit(request, pk):
    data = get_object_or_404(TODO, pk=pk)
    if data.isDone:
        messages.add_message(request, messages.WARNING, "Done task can't be edited")
        return HttpResponseRedirect(reverse('todo:index'))

    if request.method == "POST":
        form = CreateTaskForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todo:index'))
    else:
        form = CreateTaskForm(instance=data)
    return render(request, 'todo/create_edit_task.html', {'form': form})

@require_POST
def make_task_done(request, pk):
    if request.method == 'POST':
        task = get_object_or_404(TODO, pk=pk)
        if task.isDone:
            messages.add_message(request, messages.WARNING, 'The Task is already done.')
        else:
            task.isDone = True
            task.save()
            messages.add_message(request, messages.SUCCESS, 'Task is now done.')
        return HttpResponseRedirect(reverse('todo:index'))

def done_tasks_list(request):
    data = TODO.objects.filter(isDone=True).order_by('-pk')
    return render(request, "todo/done-list.html", {"data": data, 'active': 'done tasks'})

@require_POST
def make_task_in_progress(request, pk):
    if request.method == 'POST':
        task = get_object_or_404(TODO, pk=pk)
        if not task.isDone:
            messages.add_message(request, messages.WARNING, 'The Task is not done yet.')
        else:
            task.isDone = False
            task.save()
            messages.add_message(request, messages.SUCCESS, 'The task is In Progress again.')
        return HttpResponseRedirect(reverse('todo:index'))

todo/templates/todo/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet' type='text/css' href='{% static 'css/bootstrap.min.css' %}' >
    <title>{% block title %}Document{% endblock %}</title>
</head>
<body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
                <a class="navbar-brand" href="{% url 'todo:index' %}">TODO List</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link{% if active == 'new task' %} active{% endif %}" href="{% url 'todo:new_task' %}">New Task</a>
                    </li>
                    <li>
                        <a class="nav-link{% if active == 'done tasks'%} active{% endif %}" href="{% url 'todo:done_list' %}">Done tasks</a>
                    </li>
                    </ul>
                </div>
            </nav>
    <main role="main">
        {% block content %}
        <div class="container">
            <div class="col-md-4">
                You didn't add nothing to "content" block
            </div>
        </div>
        {% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

todo/templates/todo/create_edit_task.html
{% extends 'todo/base.html' %}

{% block title %}Create new task{% endblock title %}

{% block content %}
<div class="container">
    {{ form.non_field_errors }}
    <form method="post" novalidate> 
        {% csrf_token %}
        <div class="form-group">
            
            <label for="{{ form.header.id_for_label }}">Task: </label>
            {{ form.header }}
            {% if form.header.errors %}
            <script>document.getElementById("{{ form.header.id_for_label }}").className += ' is-invalid'</script>
            <div class="invalid-feedback">{{ form.header.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.description.errors}}
            <label for="{{ form.description.id_for_label }}">Desctiption: </label>
            {{ form.description }}
        </div>

        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

todo/templates/todo/create_task.html
{% extends 'todo/base.html' %}

{% block title %}Create new task{% endblock title %}

{% block content %}
{{ form.non_field_errors }}
<div class="container">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {{ form.header.errors}}
            <label for="{{ form.header.id_for_label }}">Task: </label>
            {{ form.header }}
        </div>

        <div class="form-group">
            {{ form.description.errors}}
            <label for="{{ form.description.id_for_label }}">Desctiption: </label>
            {{ form.description }}
        </div>

        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

todo/templates/todo/done-list.html
{% extends "todo/base.html" %}

{% block title %} TODO list {% endblock title %}

{% block content %}
<div class="container">
  {% if messages %}
    {% for msg in messages %}
    {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
      <strong>Congradulations!</strong> {{ msg.message }}
    </div>
    {% endif %}
    {% if msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
    <div class="alert alert-warning" role="alert">
      <strong>Opps!</strong> {{ msg.message }}
    </div>
    {% endif %}
    {% endfor %}
  {% endif %}
  {% if data %}
  <div class='card-deck'>
    {% for task in data %}
      <div class="card mb-3">
        <div class="card-header">Task #{{ forloop.counter }}</div>
        <div class="card-body">
          <h4 class="card-title">{{ task.header }}</h4>
          <p class="card-text">{{ task.description|linebreaksbr }}</p>
        </div>
        <div class="card-footer">
          <form method="post" action="{% url 'todo:make_in_progress' task.pk %}">
            {% csrf_token %}
            <button class="card-link btn btn-warning">In Progress</button>
          </form>
        </div>
      </div>
      {% cycle '' '' '' '</div><div class="card-deck">' %}
    {% endfor %}
  </div>
  {% else %}
  <h1>You have no done tasks</h1>
  {% endif %}
</div>
{% endblock content %}

todo/templates/todo/index.html
{% extends "todo/base.html" %}

{% block title %} TODO list {% endblock title %}

{% block content %}
<div class="container">
  {% if messages %}
    {% for msg in messages %}
    {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
      <strong>Congradulations!</strong> {{ msg.message }}
    </div>
    {% endif %}
    {% if msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
    <div class="alert alert-warning" role="alert">
      <strong>Opps!</strong> {{ msg.message }}
    </div>
    {% endif %}
    {% endfor %}
  {% endif %}
  {% if data %}
  <div class='card-deck'>
    {% for task in data %}
      <div class="card mb-3">
        <div class="card-header">Task #{{ forloop.counter }}</div>
        <div class="card-body">
          <h4 class="card-title">{{ task.header }}</h4>
          <p class="card-text">{{ task.description|linebreaksbr }}</p>
        </div>
        <div class="card-footer">
          <form method="post" action="{% url 'todo:make_done' task.pk %}">
            {% csrf_token %}
            <button class="card-link btn btn-success">Done</button>
            <a href="{% url 'todo:edit_task' task.pk %}" class="btn btn-info">Edit</a>
          </form>
        </div>
      </div>
      {% cycle '' '' '' '</div><div class="card-deck">' %}
    {% endfor %}
  </div>
  {% else %}
  <h1>You have no tasks yet</h1>
  {% endif %}
</div>
{% endblock content %}